"use client";

import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createSupabaseBrowserClient } from "../../../lib/supabase";
import { IMAGE_RULES, validateImage } from "@yh/core";

type Activity = { id: string; title: string; submission_ends_at: string; voting_starts_at: string; voting_ends_at: string; vote_limit: number };
type Submission = { id: string; title: string; profiles: { display_name: string } | null };

export default function ActivityPage() {
  const { slug } = useParams<{ slug: string }>(); const [activity, setActivity] = useState<Activity | null>(null); const [entries, setEntries] = useState<Submission[]>([]); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [files, setFiles] = useState<File[]>([]); const [message, setMessage] = useState("");
  useEffect(() => { const supabase = createSupabaseBrowserClient(); supabase.from("activities").select("id,title,submission_ends_at,voting_starts_at,voting_ends_at,vote_limit").eq("slug", slug).single().then(({ data, error }) => { if (error) setMessage("活动不存在或尚未公开。"); setActivity(data); if (data) supabase.from("activity_submissions").select("id,title,profiles!activity_submissions_author_id_fkey(display_name)").eq("activity_id", data.id).eq("status", "approved").then(({ data: submissions }) => setEntries((submissions as Submission[] | null) ?? [])); }); }, [slug]);
  async function submitWork(event: FormEvent) { event.preventDefault(); if (!activity) return; const supabase = createSupabaseBrowserClient(); const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return setMessage("请先登录后投稿。"); if (files.length > IMAGE_RULES.maxSubmissionImages) return setMessage(`每个作品最多上传 ${IMAGE_RULES.maxSubmissionImages} 张图片。`); const invalid = files.map(validateImage).find(Boolean); if (invalid) return setMessage(invalid); const document = { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: body }] }] }; const { data: submission, error } = await supabase.from("activity_submissions").insert({ activity_id: activity.id, author_id: auth.user.id, title, body: document }).select("id").single(); if (error || !submission) return setMessage(error?.message ?? "提交作品失败。"); for (const [position, file] of files.entries()) { const path = `${auth.user.id}/submissions/${submission.id}/${crypto.randomUUID()}`; const { error: uploadError } = await supabase.storage.from("community-images").upload(path, file); if (uploadError) return setMessage(uploadError.message); const { error: imageError } = await supabase.from("submission_images").insert({ submission_id: submission.id, storage_path: path, position }); if (imageError) return setMessage(imageError.message); } setMessage("作品已提交审核。"); setTitle(""); setBody(""); setFiles([]); }
  async function vote(submissionId: string) { const { error } = await createSupabaseBrowserClient().rpc("cast_activity_vote", { target_submission: submissionId }); setMessage(error ? error.message : "投票成功。"); }
  if (!activity) return <main className="formPage"><a href="/">返回社区</a><p>{message || "加载中..."}</p></main>;
  const now = Date.now(); const accepting = now < new Date(activity.submission_ends_at).getTime(); const voting = now >= new Date(activity.voting_starts_at).getTime() && now < new Date(activity.voting_ends_at).getTime();
  return <main className="formPage"><a href="/">返回社区</a><h1>{activity.title}</h1><p>投稿截止：{new Date(activity.submission_ends_at).toLocaleString("zh-CN")} · 可投 {activity.vote_limit} 票</p>{accepting && <form onSubmit={submitWork}><h2>提交作品</h2><label>作品标题<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>作品说明<textarea value={body} onChange={(e) => setBody(e.target.value)} required /></label><label>作品图片<input type="file" accept={IMAGE_RULES.acceptedTypes.join(",")} multiple onChange={(e) => setFiles(Array.from(e.target.files ?? []))} /></label><button>提交审核</button></form>}<h2>已审核作品</h2><div className="postList">{entries.map((entry) => <article className="postRow" key={entry.id}><div><h3>{entry.title}</h3><p>{entry.profiles?.display_name || "成员"}</p></div>{voting && <button onClick={() => vote(entry.id)}>投票</button>}</article>)}</div>{message && <p className="formNotice">{message}</p>}</main>;
}
