"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { createSupabaseBrowserClient } from "../../../lib/supabase";

type Activity = { id: string; title: string; description_markdown: string; submission_ends_at: string; voting_starts_at: string; voting_ends_at: string; vote_limit: number };
type Submission = { id: string; title: string; body_markdown: string; profiles: { display_name: string } | null };
export default function ActivityPage() {
  const { slug } = useParams<{ slug: string }>(); const [activity, setActivity] = useState<Activity | null>(null); const [entries, setEntries] = useState<Submission[]>([]); const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { let active = true; const client = createSupabaseBrowserClient(); void client.from("activities").select("id,title,description_markdown,submission_ends_at,voting_starts_at,voting_ends_at,vote_limit").eq("slug", slug).single().then(async ({ data, error }) => { if (!active) return; if (error || !data) return setMessage("活动不存在或尚未公开。"); setActivity(data); const { data: submissions } = await client.from("activity_submissions").select("id,title,body_markdown,profiles!activity_submissions_author_id_fkey(display_name)").eq("activity_id", data.id).eq("status", "approved").order("created_at", { ascending: false }); if (active) setEntries((submissions as Submission[] | null) ?? []); }); return () => { active = false; }; }, [slug]);
  async function submitWork(event: FormEvent) { event.preventDefault(); if (!activity) return; const client = createSupabaseBrowserClient(); const { data: auth } = await client.auth.getUser(); if (!auth.user) return setMessage("请先登录后投稿。"); const legacy = { type: "doc", content: [{ type: "paragraph", content: [{ type: "text", text: body }] }] }; const { error } = await client.from("activity_submissions").insert({ activity_id: activity.id, author_id: auth.user.id, title, body: legacy, body_markdown: body }); if (error) return setMessage(error.message); setTitle(""); setBody(""); setMessage("作品已提交审核。"); }
  async function vote(submissionId: string) { const { error } = await createSupabaseBrowserClient().rpc("cast_activity_vote", { target_submission: submissionId }); setMessage(error?.message ?? "投票成功。"); }
  if (!activity) return <section className="contentPage"><Link className="backLink" href="/activities">返回活动</Link><p className="emptyState">{message || "正在加载活动..."}</p></section>;
  const now = Date.now(); const accepting = now < new Date(activity.submission_ends_at).getTime(); const voting = now >= new Date(activity.voting_starts_at).getTime() && now < new Date(activity.voting_ends_at).getTime();
  return <section className="contentPage"><Link className="backLink" href="/activities">返回活动</Link><h1 className="pageTitle">{activity.title}</h1><p className="pageLead markdownBody">{activity.description_markdown}</p>{accepting && <form className="panel formGrid" onSubmit={submitWork}><h2>提交作品</h2><label>作品标题<input value={title} onChange={(event) => setTitle(event.target.value)} required /></label><label>作品说明<textarea value={body} onChange={(event) => setBody(event.target.value)} required /></label><button className="primaryButton">提交审核</button></form>}<section className="panel"><h2>公开作品</h2><p className="statusLine">{voting ? `投票开放中，每人可投 ${activity.vote_limit} 票。` : "当前未处于投票时间。"}</p>{entries.map((entry) => <article className="reply" key={entry.id}><h3>{entry.title}</h3><p>{entry.body_markdown}</p><div className="splitActions"><span className="statusLine">{entry.profiles?.display_name || "社区成员"}</span>{voting && <button className="secondaryButton" type="button" onClick={() => void vote(entry.id)}>投票</button>}</div></article>)}{entries.length === 0 && <p className="statusLine">暂时没有公开作品。</p>}</section>{message && <p className="notice">{message}</p>}</section>;
}
